### ISSUE TITLE
Parses markdown, throws errors 

### ISSUE THREAD

**Issue by crucialfelix** [prettier/prettier-atom#115]
I'm not sure why it would try to parse markdown files.  There are no code blocks in the files either.

```

00~/org/ns/bugs/nj-open-house-not-in-mailing.md27:1
LF1 deprecation
INSERT
UTF-8Spaces: 2Markdowngit+
prettier-atom: SyntaxError: Unexpected token, expected ; (2:4) 1 |

2 | why was 703259 not in daily mailing on datetime.datetime(2017, 4, 7, 8, 19, 20, 471011) | ^ 3 | 4 | mail 36724 5
SyntaxError: Unexpected token, expected ; (2:4)
  1 | 
> 2 | why was 703259 not in daily mailing on datetime.datetime(2017, 4, 7, 8, 19, 20, 471011)
    |     ^
  3 | 
  4 | mail 36724
  5 | NJ
  at Parser.pp$5.raise (/Users/crucial/.atom/packages/prettier-atom/node_modules/babylon/lib/index.js:4333:13)
  at Parser.pp.unexpected (/Users/crucial/.atom/packages/prettier-atom/node_modules/babylon/lib/index.js:1705:8)
  at Parser.pp.semicolon (/Users/crucial/.atom/packages/prettier-atom/node_modules/babylon/lib/index.js:1686:38)
  at Parser.pp$1.parseExpressionStatement (/Users/crucial/.atom/packages/prettier-atom/node_modules/babylon/lib/index.js:2182:8)
  at Parser.parseExpressionStatement (/Users/crucial/.atom/packages/prettier-atom/node_modules/babylon/lib/index.js:5324:20)
  at Parser.pp$1.parseStatement (/Users/crucial/.atom/packages/prettier-atom/node_modules/babylon/lib/index.js:1857:17)
  at Parser.parseStatement 
```

my scopes are default:
source.js, source.jsx, source.js.jsx, source.babel, source.js-semantic, text.html.basic, text.html.vue

Lovely package, thank you so much for this !

**Comment by darahak** [comment]
This could be solved if we use scopes on all formats, and not only formats on save.

**Comment by robwise** [comment]
Wait, this is happening on manual invocation of `format` and not `format-on-save`?

**Comment by crucialfelix** [comment]
It is actually happening  on first wave of a new file. Create a markdown or python file, write some stuff and then save. It opens a syntax error notification. It might be that scope of a new file isn't set yet until it completed saving.

**Comment by crucialfelix** [comment]
So this is format-on-save

**Comment by crucialfelix** [comment]
Create new markdown file.

```markdown

# new markdown file

Some text here.

No j s c r i p t
```

Save it as `test.md`

Error thrown:

<img width="1377" alt="screen shot 2017-04-22 at 12 31 22" src="https://cloud.githubusercontent.com/assets/218738/25303662/0003d0f0-2758-11e7-92f3-d1ea532124d2.png">


Callstack:
```
index.js:54 prettier-eslint [ERROR]: prettier formatting failed due to a prettier error(anonymous function) 

@ index.js:54prettify 
@ index.js:132format 
@ index.js:98(anonymous function) 
@ executePrettier.js:34exports.allowUnsafeNewFunction 
@ loophole.js:25executePrettier 
@ executePrettier.js:33executePrettierOnBufferRange 
@ executePrettier.js:46formatOnSaveIfAppropriate 
@ formatOnSave.js:36lazyFormatOnSave 
@ main.js:30(anonymous function) 
@ main.js:49module.exports.Emitter.simpleDispatch 
@ emitter.js:25module.exports.Emitter.emit 
@ emitter.js:129module.exports.TextBuffer.saveAs 
@ text-buffer.js:1069module.exports.TextEditor.saveAs 
@ text-editor.coffee:904module.exports.Pane.saveItemAs 
@ pane.coffee:690(anonymous function) 
@ pane.coffee:1module.exports.Pane.saveItem 
@ pane.coffee:672(anonymous function) 
@ pane.coffee:1module.exports.Pane.saveActiveItem 
@ pane.coffee:639saveActivePaneItem 
@ workspace.js:851core:save 
@ register-default-commands.coffee:78module.exports.CommandRegistry.handleCommandEvent 
@ command-registry.coffee:255(anonymous function) 
@ command-registry.coffee:1module.exports.KeymapManager.dispatchCommandEvent 
@ keymap-manager.js:599module.exports.KeymapManager.handleKeyboardEvent 
@ keymap-manager.js:390module.exports.WindowEventHandler.handleDocumentKeyEvent 
@ window-event-handler.coffee:76(anonymous function) 
@ window-event-handler.coffee:1
```

**Comment by crucialfelix** [comment]
The bug:

https://github.com/prettier/prettier-atom/blob/master/dist/helpers.js#L129

```
var isCurrentScopeEmbeddedScope = function isCurrentScopeEmbeddedScope(editor) {
  return EMBEDDED_SCOPES.includes(getCurrentScope(editor));
};
```
perhaps

```
var isCurrentScopeEmbeddedScope = function isCurrentScopeEmbeddedScope(editor) {
  const currentScope = getCurrentScope(editor);
  return currentScope && EMBEDDED_SCOPES.includes(currentScope);
};
```
but I have to test that. Not sure if I can find time to setup and do a PR but I will see.

**Comment by darahak** [comment]
Format on first save is supposed to be fixed on https://github.com/prettier/prettier-atom/pull/127
Can you try the latest version? (0.29.0)

**Comment by crucialfelix** [comment]
yes, thanks !
