### ISSUE TITLE
Failed to load the prettier-atom package

### ISSUE THREAD

**Issue by hamutinnikov** [prettier/prettier-atom#154]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.30.0

### Stack Trace

Failed to load the prettier-atom package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/prettier-atom/dist/helpers.js:3:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/prettier-atom/dist/statusTile.js:3:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/prettier-atom/dist/main.js:9:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
```

### Non-Core Packages

```
autoclose-html 0.23.0 
busy-signal 1.4.1 
color-picker 2.2.5 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.58.0 
linter 2.1.4 
linter-eslint 8.1.7 
linter-ui-default 1.2.3 
minimap 4.28.1 
prettier-atom 0.30.0 
```

**Comment by robwise** [comment]
@hamutinnikov Can you install atom-linter and see if it fixes it?

**Comment by robwise** [comment]
According to Steelbrain, we should implement this ASAP so this doesn't happen to other people: https://www.npmjs.com/package/atom-package-deps

**Comment by robwise** [comment]
Closing, please re-open if you are still having trouble

**Comment by robwise** [comment]
@a-eid can you try restarting Atom an additional time? One user reports this solved the problem for him, although I admit I don't really understand what's going on here.

**Comment by Anujraval24** [comment]
Severity | Provider | Description | Line
-- | -- | -- | --

**Comment by Anujraval24** [comment]
Error: Cannot find module 'babel-runtime/helpers/asyncToGenerator'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/anujr/AppData/Local/atom/app-1.30.0/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\native-compile-cache.js:66:33)
    at Object.<anonymous> (C:\Users\anujr\.atom\packages\prettier-atom\dist\main.js:3:26)
    at Object.<anonymous> (C:\Users\anujr\.atom\packages\prettier-atom\dist\main.js:164:3)
    at Module.get_Module._compile (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .js] (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/anujr/AppData/Local/atom/app-1.30.0/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\static\<embedded>:96:26)
    at Package.requireMainModule (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:782:33)
    at measure (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:143:22)
    at Package.measure (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:88:25)
    at Package.load (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\package.js:129:16)
    at PackageManager.loadAvailablePackage (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\package-manager.js:618:16)
    at config.transact (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\package-manager.js:531:20)
    at Config.transact (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\config.js:819:20)
    at PackageManager.loadPackages (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\package-manager.js:529:23)
    at loadStatePromise.loadState.then (C:\Users\anujr\AppData\Local\atom\app-1.30.0\resources\app\src\atom-environment.js:837:27)
    at <anonymous>

**Comment by robwise** [comment]
@Anujraval24 Can you make a new issue? Your trace doesn't seem related to the OP.
