### ISSUE TITLE
Can't save file

### ISSUE THREAD

**Issue by tbillington** [prettier/prettier-atom#190]
![screen shot 2017-06-09 at 1 54 23 pm](https://user-images.githubusercontent.com/2771466/26960509-477a1532-4d1b-11e7-9457-c7c1c17dac33.png)

[Enter steps to reproduce:]

1. Have outdated prettier-atom
2. Update prettier-atom
3. Try to save file

Prettier-atom is asking me to restart atom to get updates, but it won't let me save my file so I can restart.

I have run on save disabled.

I had to disable the extension to be able to save my file.

Can prettier-atom operations be wrapped in a try catch to prevent them from bringing down core editor functions?

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.32.0

### Stack Trace

Uncaught TypeError: Expected a function

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1095

TypeError: Expected a function
    at Function.su (/packages/prettier-atom/node_modules/lodash/lodash.min.js:70:197)
    at /packages/prettier-atom/dist/formatOnSave/shouldFormatOnSave.js:42:241)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at /packages/prettier-atom/dist/formatOnSave/index.js:11:26)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:1)
    at lazyFormatOnSave (/packages/prettier-atom/dist/main.js:37:37)
    at /packages/prettier-atom/dist/main.js:101:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1119:1)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:1)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:925:1)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:780:1)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:1)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:1)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1498:1)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:38 editor:newline (input.hidden-input)
  3x -0:33.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.26 
atom-typescript 11.0.3 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.7 
go-debug 1.4.3 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
ide-purescript 0.17.2 
intentions 1.1.2 
language-docker 1.1.8 
language-elm 1.5.0 
language-javascript-jsx 0.3.7 
language-protobuf 0.7.1 
language-purescript 0.8.2 
language-rust 0.4.10 
linter 2.1.4 
linter-eslint 8.2.1 
linter-flow 5.6.0 
linter-php 1.3.2 
linter-rust 0.8.0 
linter-ui-default 1.6.0 
nuclide 0.232.0 
php-twig 4.0.0 
pigments 0.39.1 
prettier-atom 0.32.0 
racer 0.20.0 
react 0.16.2 
```

**Comment by robwise** [comment]
@darahak do you think we should basically just wrap `formatOnSave` in a massive outer try-catch?

**Comment by darahak** [comment]
Looks like the way to go.
We should just ensure any error gets properly reported by the catch handler.

**Comment by robwise** [comment]
Roger that

**Comment by peterpme** [comment]
:wave: I have the same issue. Disabling prettier-atom fixed this for me
