### ISSUE TITLE
onDidChangeActiveTextEditor only available in latest Atom

### ISSUE THREAD

**Issue by darahak** [prettier/prettier-atom#205]
[atom.workspace.onDidChangeActiveTextEditor](https://atom.io/docs/api/v1.18.0/Workspace#instance-onDidChangeActiveTextEditor) only exists on Atom 1.18.0.

On older versions, we get this error:

### Stack Trace

Failed to activate the status-bar package

```
At atom.workspace.onDidChangeActiveTextEditor is not a function

TypeError: atom.workspace.onDidChangeActiveTextEditor is not a function
    at attachStatusTile (/packages/prettier-atom/dist/main.js:80:38)
    at Object.consumeStatusBar (/packages/prettier-atom/dist/main.js:132:5)
    at Provider.module.exports.Provider.provide (<embedded>:107964:58)
    at ServiceHub.module.exports.ServiceHub.provide (<embedded>:68057:26)
    at Package.module.exports.Package.activateServices (<embedded>:68554:77)
    at Package.module.exports.Package.activateNow (<embedded>:68364:22)
    at <embedded>:68333:38
    at Package.module.exports.Package.measure (<embedded>:68207:21)
    at <embedded>:68326:32
    at Package.module.exports.Package.activate (<embedded>:68323:40)
    at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20446:40)
    at <embedded>:20427:35
    at Config.module.exports.Config.transactAsync (<embedded>:17520:24)
    at PackageManager.module.exports.PackageManager.activatePackages (<embedded>:20422:25)
    at PackageManager.module.exports.PackageManager.activate (<embedded>:20404:52)
    at <embedded>:1085:34

```

### Commands

```
     -0:07.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

**Comment by robwise** [comment]
I guess we can just wrap this subscription with a check of the atom version first? And then just don't display the tooltip otherwise? Are a lot of people using versions of Atom older than 1.18.0?

**Comment by darahak** [comment]
I don't know if it happens a lot, but I think it's still worth fixing for the few people that might experience this bug. It's possible some people stick to an older version if there are regressions that remain unfixed for example.

I'll read the docs and see if I can find an alternative.
If I can't find any, I'll apply your suggestion.
