### ISSUE TITLE
TypeError: isCurrentScopeJsonScope is not a function

### ISSUE THREAD

**Issue by michaeljcalkins** [prettier/prettier-atom#214]
This just started happening and I'm not sure what caused it.  In every React JavaScript file I get this error.  It prevents formatting from occurring.  I restarted Atom and it worked again.

```
TypeError: isCurrentScopeJsonScope is not a function
    at buildPrettierOptions (/Users/michaelcalkins/.atom/packages/prettier-atom/dist/executePrettier/buildPrettierOptions.js:41:7)
    at buildPrettierEslintOptions (/Users/michaelcalkins/.atom/packages/prettier-atom/dist/executePrettier/buildPrettierEslintOptions.js:17:30)
    at /Users/michaelcalkins/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:23:27
    at exports.allowUnsafeNewFunction (/Users/michaelcalkins/.atom/packages/custom-title/node_modules/loophole/lib/loophole.js:25:14)
    at executePrettierEslint (/Users/michaelcalkins/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:22:10)
    at executePrettierOrPrettierEslint (/Users/michaelcalkins/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:29:32)
    at executePrettierOnBufferRange (/Users/michaelcalkins/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:38:21)
    at formatOnSaveIfAppropriate (/Users/michaelcalkins/.atom/packages/prettier-atom/dist/formatOnSave/index.js:14:122)
    at lazyFormatOnSave (/Users/michaelcalkins/.atom/packages/prettier-atom/dist/main.js:39:15)
    at /Users/michaelcalkins/.atom/packages/prettier-atom/dist/main.js:103:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1119:26)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:25)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:925:32)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:780:24)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:3:65)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:763:25)
    at Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1548:46)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:236:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

<details>
```
Atom version: 1.18.0
prettier-atom version: undefined
prettier version: undefined
prettier-eslint version: undefined
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false
  },
  "prettierEslintOptions": {
    "prettierLast": false
  },
  "prettierOptions": {
    "semi": false,
    "singleQuote": true,
    "bracketSpacing": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon"
  },
  "useEslint": true,
  "silenceErrors": false,
  "useEditorConfig": true
}
```
</details>

**Comment by dodekeract** [comment]
Same here, first time I've seen this is today.

**Comment by robwise** [comment]
@michaeljcalkins Do you mean you upgraded, didn't restart Atom, then got this error, then restarted Atom, and now it works?

**Comment by michaeljcalkins** [comment]
@robwise I do not remember what happened first and it hasn't happened again.  It just stopped working, I turned on prettier-atom errors, and then this appeared.  

If you released an update that was probably the issue.  I was doing some package work and I had to restart Atom to make it work right sometimes.

**Comment by robwise** [comment]
Yes, Atom must always be restarted after updating a package. I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
