### ISSUE TITLE
Whitelist globs not matching

### ISSUE THREAD

**Issue by pwolfert** [prettier/prettier-atom#243]
I'm not sure if the whitelist globs are working, and I'm not sure how to test it either. I know the globs themselves match when using `minimatch`, but format on save doesn't work on those files. I've also tried blacklisting what I don't want, and that doesn't seem to work. My globs look like:

```
/Users/USERNAME/Sites/PROJECT/**/*
```

Does it not use the full path? I've also tried just `**/PROJECT/**/*`.

Output of `Prettier: Debug`—and it looks like it's a problem with `Prettier: Debug` itself and has nothing to do with my problem, but it may be relevant:
<details>
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.29.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'package.json'

```
At fs.js:640

Error: ENOENT: no such file or directory, open 'package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at /packages/prettier-atom/node_modules/load-json-file/index.js:11:38)
    at Function.module.exports.sync (/packages/prettier-atom/node_modules/read-pkg/index.js:40:25)
    at getDebugInfo (/packages/prettier-atom/dist/helpers.js:196:34)
    at displayDebugInfo (/packages/prettier-atom/dist/displayDebugInfo.js:7:14)
    at /packages/prettier-atom/dist/main.js:49:3)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:56.7.0 core:save (input.hidden-input)
     -1:55.9.0 core:undo (input.hidden-input)
  2x -1:54.5.0 core:save (input.hidden-input)
     -1:51.5.0 core:undo (input.hidden-input)
     -1:50.8.0 core:save (input.hidden-input)
     -0:19.6.0 command-palette:toggle (input.hidden-input)
     -0:16.9.0 core:confirm (input.hidden-input)
     -0:16.9.0 prettier:debug (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.3.0 
change-case 0.6.5 
flow-ide 1.4.1 
intentions 1.1.2 
language-babel 2.57.7 
language-javascript-jsx 0.3.7 
language-pug 0.0.21 
linter 2.1.2 
linter-ui-default 1.2.2 
minimap 4.27.1 
prettier-atom 0.29.0 
save-workspace 0.4.0 
selection-highlight 0.1.6 
simple-drag-drop-text 0.3.4 
split-diff 1.3.0 
```

</details>

Thanks!

**Comment by robwise** [comment]
We actually switched to `ignore-globs` so we aren't using `minimatch` anymore. Are you sure you haven't enabled `Only format if Prettier is found in the dependencies` and that these files aren't in an eslintignore (or you haven't enabled that option)?

**Comment by pwolfert** [comment]
`Only format if Prettier is found in the dependencies` isn't an option for me. I've got the defaults except for `Format on Save` being enabled. Screenshot (minus the globs):

<img width="867" alt="screen shot 2017-08-01 at 3 22 11 pm" src="https://user-images.githubusercontent.com/7595652/28849732-525ed3e4-76cd-11e7-966a-2902f66055f7.png">

And I have no `.eslintignore` file in my project.

**Comment by robwise** [comment]
@kentcdodds Have you had any problems with whitelisting globs? I think you use this feature a lot?

**Comment by pwolfert** [comment]
Updated to `0.37.0`, and still no dice.

**Comment by pwolfert** [comment]
Upgrading gave me this option, which works for me:

<img width="810" alt="screen shot 2017-08-03 at 9 32 00 am" src="https://user-images.githubusercontent.com/7595652/28932540-b1288c46-782e-11e7-868f-9c0e83ab753f.png">

**Comment by darahak** [comment]
I don't understand how this solved your issue.
Does somebody have any clue?

**Comment by robwise** [comment]
I agree but I can't reproduce the original issue (it seems to work fine AFAICT). I will close for now and we can reopen if others have this issue.
