### ISSUE TITLE
Atom file saving fails after upgrading to latest prettier-atom

### ISSUE THREAD

**Issue by kaspar-naaber** [prettier/prettier-atom#315]
I did an update in this morning and after. When I try to save any file it will output the following to the console and save is not triggered:

<details>

```
/Users/kaspar/.atom/packages/prettier-atom/node_modules/babel-polyfill/lib/index.js:10 Uncaught (in promise) Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/Users/kaspar/.atom/packages/prettier-atom/node_modules/babel-polyfill/lib/index.js:10:9)
    at Object.<anonymous> (/Users/kaspar/.atom/packages/prettier-atom/node_modules/babel-polyfill/lib/index.js:29:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/kaspar/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:5:1)
    at Object.<anonymous> (/Users/kaspar/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:155:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/kaspar/.atom/packages/prettier-atom/dist/executePrettier/index.js:3:36)
    at Object.<anonymous> (/Users/kaspar/.atom/packages/prettier-atom/dist/executePrettier/index.js:10:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/kaspar/.atom/packages/prettier-atom/dist/formatOnSave/index.js:12:17)
    at Object.<anonymous> (/Users/kaspar/.atom/packages/prettier-atom/dist/formatOnSave/index.js:34:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at lazyFormatOnSave (/Users/kaspar/.atom/packages/prettier-atom/dist/main.js:38:37)
    at /Users/kaspar/.atom/packages/prettier-atom/dist/main.js:120:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:154:50)
    at Emitter.module.exports.Emitter.emitAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:157:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1288:38
```
</details>

<details>

```
prettier-atom: details on current install
Atom version: 1.22.1
prettier-atom version: 0.43.0
prettier version: 1.9.0
prettier-eslint version: 8.2.3
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "showInStatusBar": true,
    "enabled": false,
    "respectEslintignore": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "useEslint": true,
  "useStylelint": false,
  "useEditorConfig": true,
  "prettierOptions": {
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon"
  },
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
```

</details>

**Comment by darahak** [comment]
Sorry about this! I think babel-polyfill was introduced with https://github.com/prettier/prettier-atom/pull/311.
It's a known issue (see https://github.com/babel/babel/issues/4019), but we should be able to mitigate it by applying [this](https://github.com/babel/babel/issues/4019#issuecomment-245409648).

I'm not able to make the change now, so feel free to make a PR or wait for the fix!

**Comment by robwise** [comment]
@darahak I can bang this one out real quick
