### ISSUE TITLE
Error: Comment location overlaps with node location

### ISSUE THREAD

**Issue by JNaftali** [prettier/prettier-atom#323]
Unfortunately I don't know for sure that this issue doesn't lie with Prettier or Atom - I can't figure out why it happens sometimes. I'm game to investigate more if someone tells me where to look. Here's the error message copied from the console:

<details>/Users/lab/.atom/packages/prettier-atom/dist/executePrettier/handleError.js:55 Error: Comment location overlaps with node location
    at decorateComment (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1309:11)
    at decorateComment (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1284:7)
    at decorateComment (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1284:7)
    at decorateComment (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1284:7)
    at decorateComment (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1284:7)
    at decorateComment (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1284:7)
    at decorateComment (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1284:7)
    at decorateComment (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1284:7)
    at comments.forEach (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1357:5)
    at Array.forEach (native)
    at Object.attach (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:1351:12)
    at attachComments (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:27587:14)
    at formatWithCursor (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:27671:23)
    at format (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:27697:10)
    at Object.format (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier/index.js:27936:12)
    at prettify (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier-eslint/dist/index.js:155:29)
    at format (/Users/lab/.atom/packages/prettier-atom/node_modules/prettier-eslint/dist/index.js:141:20)
    at /Users/lab/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:42:12
    at exports.allowUnsafeNewFunction (/Users/lab/.atom/packages/prettier-atom/node_modules/loophole/lib/loophole.js:25:14)
    at executePrettierEslint (/Users/lab/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:41:10)
    at _callee$ (/Users/lab/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:75:27)
    at tryCatch (/Users/lab/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/lab/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/lab/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/lab/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/lab/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/lab/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/lab/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at executePrettierOrIntegration (/Users/lab/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:97:17)
    at _callee2$ (/Users/lab/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:111:20)
    at tryCatch (/Users/lab/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/lab/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/lab/.atom/packages/prettier-atom/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/lab/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/lab/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/lab/.atom/packages/prettier-atom/node_modules/core-js/library/modules/_export.js:35:28)
    at /Users/lab/.atom/packages/prettier-atom/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at executePrettierOnBufferRange (/Users/lab/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:157:18)
    at callAppropriatePrettierExecutor (/Users/lab/.atom/packages/prettier-atom/dist/formatOnSave/index.js:22:91)
    at r (/Users/lab/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5:165)
    at /Users/lab/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:97:162
    at r (/Users/lab/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5:165)
    at /Users/lab/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:63:325
    at /Users/lab/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:49:144
    at /Users/lab/.atom/packages/prettier-atom/dist/formatOnSave/index.js:29:12
    at attemptWithErrorNotification (/Users/lab/.atom/packages/prettier-atom/dist/atomInterface/index.js:142:10)
    at safeFormatOnSaveIfAppropriate (/Users/lab/.atom/packages/prettier-atom/dist/formatOnSave/index.js:28:10)
    at lazyFormatOnSave (/Users/lab/.atom/packages/prettier-atom/dist/main.js:39:15)
    at /Users/lab/.atom/packages/prettier-atom/dist/main.js:120:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:154:50)
    at Emitter.module.exports.Emitter.emitAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:157:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1288:38</details>

Here's the output of Prettier: Debug
<details>
Atom version: 1.22.1
prettier-atom version: 0.43.1
prettier version: 1.9.2
prettier-eslint version: 8.2.6
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "showInStatusBar": true,
    "respectEslintignore": true,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss",
      "source.css.postcss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "markdownScopes": [
      "source.md",
      "source.gfm",
      "text.md"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "singleQuote": true,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "printWidth": 80,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon"
  },
  "useEslint": true,
  "useStylelint": false,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
</details>

As I said, please let me know what I can do to make this bug report more useful or where I can start looking to find the problem myself. Thanks for maintaining the prettier integration for Atom, I love it!

**Comment by robwise** [comment]
@JNaftali The error seems to be coming out of the Prettier package, so unless prettier-atom is giving it bad data, my hunch is that it is a Prettier issue. I would try and search the Prettier repo for this text: `Comment location overlaps with node location at decorateComment` and see if you can tell what they're talking about? I will leave this open for now since we're not 100% sure whether or not it's a prettier-atom problem.

**Comment by JNaftali** [comment]
@robwise thanks for your help. I should have searched for the error in the prettier repo for the error before bothering you - sure enough, there's https://github.com/prettier/prettier/issues/2347. I'm gonna close this now because it seems pretty certain that the issue has nothing to do with this package. Thanks for doing what you do!
