### ISSUE TITLE
Cannot read property 'pos' of undefined

### ISSUE THREAD

**Issue by mykter** [prettier/prettier-atom#326]
Steps to reproduce:
1. Create a new file, test.d.ts
2. Enter the following text: `declare function test(): Promise<>;`
3. Press save. The contents of the file are replaced with the following stacktrace, and the file is saved:

<details>
TypeError: Cannot read property 'pos' of undefined
    at r (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1247254)
    at Object.V [as findNextToken] (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1247314)
    at Object.findNextToken (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:10993)
    at i (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1555443)
    at Object.keys.filter.forEach.e (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1586733)
    at Array.forEach (native)
    at /home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1586607
    at e (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1587020)
    at n (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1555174)
    at r (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1555243)
    at e (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1561590)
    at n (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1555174)
    at p.statements.forEach.e (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1558548)
    at Array.forEach (native)
    at e (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1558528)
    at astConverter (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1587339)
    at Object.parse$1 [as parse] (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:17974)
    at tryParseTypeScript (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:18320)
    at parse (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:18085)
    at Object.parse (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/index.js:3820:12)
    at formatWithCursor (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/index.js:21840:22)
    at format (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/index.js:21880:10)
    at Object.format (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/index.js:22105:12)
    at prettify (/home/mike/.atom/packages/prettier-atom/node_modules/prettier-eslint/dist/index.js:149:29)
    at format (/home/mike/.atom/packages/prettier-atom/node_modules/prettier-eslint/dist/index.js:135:20)
    at /home/mike/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:26:12
    at exports.allowUnsafeNewFunction (/home/mike/.atom/packages/prettier-atom/node_modules/loophole/lib/loophole.js:25:14)
    at executePrettierEslint (/home/mike/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:25:10)
    at executePrettierOrPrettierEslint (/home/mike/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:32:32)
    at executePrettierOnBufferRange (/home/mike/.atom/packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:41:21)
    at callAppropriatePrettierExecutor (/home/mike/.atom/packages/prettier-atom/dist/formatOnSave/index.js:22:91)
    at r (/home/mike/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5:165)
    at /home/mike/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:97:162
    at r (/home/mike/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:5:165)
    at /home/mike/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:63:325
    at /home/mike/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:49:144
    at /home/mike/.atom/packages/prettier-atom/dist/formatOnSave/index.js:29:12
    at attemptWithErrorNotification (/home/mike/.atom/packages/prettier-atom/dist/atomInterface/index.js:130:10)
    at safeFormatOnSaveIfAppropriate (/home/mike/.atom/packages/prettier-atom/dist/formatOnSave/index.js:28:10)
    at lazyFormatOnSave (/home/mike/.atom/packages/prettier-atom/dist/main.js:39:15)
    at /home/mike/.atom/packages/prettier-atom/dist/main.js:120:14
    at Function.module.exports.Emitter.simpleDispatch (/snap/atom/106/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.<anonymous> (/snap/atom/106/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:154:50)
    at Emitter.module.exports.Emitter.emitAsync (/snap/atom/106/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:157:18)
    at /snap/atom/106/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1283:38
</details>

`Prettier: Debug` output:
<details>
Atom version: 1.23.1
prettier-atom version: 0.40.0
prettier version: 1.7.4
prettier-eslint version: 8.2.0
prettier-atom configuration: {
  "formatOnSaveOptions": {
    "enabled": true,
    "respectEslintignore": true,
    "showInStatusBar": false,
    "javascriptScopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic",
      "text.html.basic",
      "text.html.vue"
    ],
    "typescriptScopes": [
      "source.ts",
      "source.tsx",
      "source.ts.tsx"
    ],
    "cssScopes": [
      "source.css",
      "source.less",
      "source.css.less",
      "source.scss",
      "source.css.scss"
    ],
    "jsonScopes": [
      "source.json"
    ],
    "graphQlScopes": [
      "source.graphql"
    ],
    "excludedGlobs": [],
    "whitelistedGlobs": [],
    "isDisabledIfNotInPackageJson": false,
    "isDisabledIfNoConfigFile": false
  },
  "prettierOptions": {
    "printWidth": 100,
    "singleQuote": false,
    "bracketSpacing": true,
    "semi": true,
    "useTabs": false,
    "jsxBracketSameLine": false,
    "tabWidth": "auto",
    "trailingComma": "none",
    "parser": "babylon"
  },
  "useEslint": true,
  "useEditorConfig": true,
  "prettierEslintOptions": {
    "prettierLast": false
  }
}
</details>

**Comment by robwise** [comment]
@mykter Can you do me a favor and see what happens if you try to run prettier on this directly from the command line? (Checking for not only whether or not the error happens, but also whether the error is thrown versus is returned as the new text without throwing, as seems to be the case here)

**Comment by mykter** [comment]
```
~/.atom/packages/prettier-atom/node_modules/prettier/bin$ ./prettier.js test.d.ts 2> err.txt

~/.atom/packages/prettier-atom/node_modules/prettier/bin$ cat err.txt 
Ignored unknown option: jsxSameLine
test.d.ts: TypeError: Cannot read property 'pos' of undefined
    at r (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1247161)
    at Object.V [as findNextToken] (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1247221)
    at Object.findNextToken (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:10900)
    at i (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1555350)
    at Object.keys.filter.forEach.e (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1586640)
    at Array.forEach (native)
    at /home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1586514
    at e (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1586927)
    at n (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1555081)
    at r (/home/mike/.atom/packages/prettier-atom/node_modules/prettier/parser-typescript.js:1:1555150)
```

Running as `./prettier.js --write test.d.ts` leads to the error on stderr and no change to the file.

**Comment by robwise** [comment]
Since this appears to be a Prettier error I'm going to go ahead and close for now. Please reopen if something needs to be addressed in this repo.

**Comment by mykter** [comment]
I'd suggest that prettier-atom shouldn't replace the contents of files with prettier errors. In the same way that running prettier on this file doesn't change the file, prettier-atom shouldn't either.

Or to put it another way, prettier-atom shouldn't turn parsing errors in prettier into data loss errors for prettier-atom users.

**Comment by mykter** [comment]
When I tested it back in Dec it  prettier was only putting the error out on stderr, and didn't touch the file. But I guess that's a different interface to the API used in prettier-atom. I'll let you know if it happens again!

**Comment by robwise** [comment]
Okay please do and we'll address!
