### ISSUE TITLE
Failed to activate the prettier-atom package

### ISSUE THREAD

**Issue by broomface** [prettier/prettier-atom#331]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.43.1

### Stack Trace

Failed to activate the prettier-atom package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at loadPackageDeps (/packages/prettier-atom/dist/main.js:100:5)
    at Object.activate (/packages/prettier-atom/dist/main.js:110:3)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:255:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.15 
intentions 1.1.5 
language-fish-shell 1.0.5 
linter 2.2.0 
linter-js-blyss 10.0.0 
linter-ui-default 1.6.10 
open-in-browser 0.5.2 
platformio-ide-terminal 2.8.0 
prettier-atom 0.43.1 
tomorrow-night-eighties-syntax 1.0.2 
```

**Comment by robwise** [comment]
@broomface Can you try uninstalling the package and reinstalling? Seems like something got messed up somehow.

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.

**Comment by ftaiolivista** [comment]
Same here. Started after upgrading Atom 1.36.0

Tested reinstalling the plugin the plugin but same result

**Comment by stephen304** [comment]
I just got this same issue when starting atom today, and the error directed me to this issue. I reinstalled the package, but as soon as it was installed, the error popped up again:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 4.1.1
**OS**: linux 5.0.7-arch1-1-ARCH
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.56.4


### Stack Trace

Failed to activate the prettier-atom package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at /packages/prettier-atom/node_modules/prettier/index.js:40036:21
    at createCommonjsModule (/packages/prettier-atom/node_modules/prettier/index.js:192:35)
    at /packages/prettier-atom/node_modules/prettier/index.js:39843:18)
    at /packages/prettier-atom/node_modules/prettier/index.js:41849:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/helpers/getPrettierInstance.js:4:25)
    at /packages/prettier-atom/dist/helpers/getPrettierInstance.js:20:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/helpers/index.js:9:29)
    at /packages/prettier-atom/dist/helpers/index.js:20:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/prettier-atom/dist/statusTile/updateStatusTileScope.js:3:56)
```

### Commands

```
     -0:56.9.0 intentions:highlight (input.hidden-input)
     -0:56.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:55.8.0 editor:consolidate-selections (input.hidden-input)
     -0:55.8.0 core:cancel (input.hidden-input)
     -0:55.3.0 intentions:highlight (input.hidden-input)
     -0:55 settings-view:open (input.hidden-input)
     -0:41.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
better-git-blame 0.4.7 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.0 
linter-ui-default 1.7.1 
prettier-atom 0.56.4 
python-yapf 0.14.0 
sort-lines 0.19.0 
```

**Comment by ftaiolivista** [comment]
@stephen304  It's a different problem. Follow #493
