### ISSUE TITLE
Failed to load: Cannot find module './statusTile' 

### ISSUE THREAD

**Issue by yuchi** [prettier/prettier-atom#372]
Steps to reproduce:

1. Update from `0.48` to `0.49.2`
2. Restart Atom
3. ~~Profit~~ Error shown below :(

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.49.2

### Stack Trace

Failed to load the prettier-atom package

```
At Cannot find module './statusTile'

Error: Cannot find module './statusTile'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/prettier-atom/dist/main.js:9:17)
    at /packages/prettier-atom/dist/main.js:181:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:832:34
```

### Commands

```
     -0:48.7.0 editor:select-to-end-of-line (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -0:45.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:04.8.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
apex-muted-ui 0.1.4 
apex-syntax 0.2.0 
apex-ui 1.0.3 
apex-ui-slim 0.0.0 
atom-dark-flat-ui 2.1.0 
atom-ide-ui 0.8.0 
atom-panda-syntax 0.18.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
change-case 0.6.5 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
editorconfig 2.2.2 
fizzy 0.21.0 
gl-light-syntax 3.0.0 
gulp-control 0.5.0 
highlight-line 0.12.0 
ide-flowtype 0.18.0 
ide-typescript 0.7.2 
intentions 1.1.5 
language-babel 2.83.1 
language-diff 0.7.0 
language-gradle 0.0.5 
language-jade 0.7.2 
language-pug 0.0.21 
language-rust 0.4.12 
language-soy 0.3.2 
language-velocity 0.1.2 
linter 2.2.0 
linter-eslint 8.4.1 
linter-stylelint 4.2.0 
linter-ui-default 1.6.10 
melanite-syntax 0.4.4 
minimap 4.29.7 
minimap-git-diff 4.3.1 
mobile-preview 0.4.0 
monocolor-light-blue-syntax 2.0.0 
neutron-syntax 0.7.0 
neutron-ui 0.4.0 
no-title-bar 1.11.4 
now-light-syntax 1.1.4 
paper-flat-ui 1.3.6 
paraiso-dark 2.0.2 
paraiso-light 2.0.2 
perfectionist 1.4.0 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
prettier-atom 0.49.2 
pretty-json 1.6.4 
salmon-on-ice-syntax 0.2.1 
semico-dark-ui 0.46.0 
seti-syntax 1.1.3 
seti-ui 1.10.0 
sort-lines 0.18.0 
space-tab 0.4.2 
spacegray-dark-ui 0.13.0 
Stylus 3.1.1 
teletype 0.6.0 
travis-ci-status 1.3.1 
tron-legacy-theme 0.8.0 
tron-theme 0.3.3 
unity-ui 2.1.11 
valign 1.1.3 
visual-bell 1.0.0 
Zen 0.18.0 
```

**Comment by yuchi** [comment]
By the way, closing and restarting Atom ___again___ _solves_ the issue.

**Comment by robwise** [comment]
@yuchi permanently solves the issue or just temporary? I'm worried this might be some sort of weird Atom update glitch or something. We've been getting a lot of similar issues to this where people are able to resolve without us really changing anything.

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
