### ISSUE TITLE
Uncaught TypeError: Expected a function

### ISSUE THREAD

**Issue by iatpatelishan** [prettier/prettier-atom#484]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.56.2

### Stack Trace

Uncaught TypeError: Expected a function

```
At /Users/ishanpatel/.atom/packages/prettier-atom/node_modules/lodash/lodash.min.js:97

TypeError: Expected a function
    at /packages/prettier-atom/node_modules/lodash/lodash.min.js:97:300
    at /packages/prettier-atom/node_modules/lodash/lodash.min.js:6:348)
    at Function.An.cond (/packages/prettier-atom/node_modules/lodash/lodash.min.js:97:251)
    at /packages/prettier-atom/dist/manualFormat/index.js:14:51)
    at /packages/prettier-atom/dist/manualFormat/index.js:17:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at HTMLElement.lazyFormat (/packages/prettier-atom/dist/main.js:28:25)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212945)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209079)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:285196)
```

### Commands

```
  2x -5:11.1.0 core:save (input.hidden-input)
     -4:54.7.0 core:cut (input.hidden-input)
     -4:54.3.0 core:save (input.hidden-input)
     -3:52.4.0 core:cut (input.hidden-input)
  2x -3:46.8.0 editor:newline (input.hidden-input)
     -3:46.4.0 core:paste (input.hidden-input)
     -3:40.5.0 core:copy (input.hidden-input)
     -3:38.9.0 core:paste (input.hidden-input)
     -3:38.4.0 core:save (input.hidden-input)
     -2:23 core:select-all (input.hidden-input)
     -2:01.7.0 code-format:format-code (input.hidden-input)
     -0:52.5.0 platformio-ide-terminal:new (input.hidden-input)
     -0:49.4.0 platformio-ide-terminal:paste (div.)
     -0:12.6.0 prettier:toggle-format-on-save (textarea.)
     -0:09.6.0 prettier:format (input.hidden-input)
     -0:09.0 datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-jest-snippets 2.1.0 
autocomplete-modules 2.2.6 
busy-signal 2.0.0 
es6-javascript 1.0.0 
file-icons 2.1.27 
git-history 3.3.0 
go-plus 6.1.0 
goto-definition 1.3.4 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.0.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
platformio-ide-terminal 2.8.4 
prettier-atom 0.56.2 
pretty-json 2.0.3 
react 0.18.0 
tab-foldername-index 3.3.0 
teletype 0.13.3 
```

**Comment by robwise** [comment]
I am going to close this for now, please let me know if there is still something that needs to be addressed and I will reopen.
