### ISSUE TITLE
Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by PepijnSenders** [prettier/prettier-atom#508]
[Enter steps to reproduce:]

1. `cmd+shift+p`
2. `Prettier: debug`

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.57.0

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /Users/psenders/.atom/packages/prettier-atom/dist/displayDebugInfo/index.js:27

TypeError: Cannot read property 'version' of undefined
    at getDebugInfo (/packages/prettier-atom/dist/displayDebugInfo/index.js:27:51)
    at HTMLElement.displayDebugInfo (/packages/prettier-atom/dist/displayDebugInfo/index.js:36:11)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348418)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:697714)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:871573)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:866452)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348418)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1247210)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1243344)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:283624)
```

### Commands

```
     -0:28.4.0 snippets:next-tab-stop (input.hidden-input)
     -0:28.4.0 snippets:expand (input.hidden-input)
     -0:28.4.0 editor:indent (input.hidden-input)
  2x -0:27.3.0 core:backspace (input.hidden-input)
     -0:25.5.0 core:save (input.hidden-input)
     -0:21.5.0 editor:newline (input.hidden-input)
     -0:20.8.0 core:save (input.hidden-input)
     -0:12.1.0 command-palette:toggle (input.hidden-input)
     -0:11.1.0 core:move-down (input.hidden-input)
     -0:10.9.0 core:confirm (input.hidden-input)
     -0:10.9.0 prettier:format (input.hidden-input)
     -0:09.4.0 command-palette:toggle (input.hidden-input)
     -0:08.3.0 core:move-down (input.hidden-input)
     -0:08.0 core:move-up (input.hidden-input)
     -0:07.7.0 core:confirm (input.hidden-input)
     -0:07.7.0 prettier:debug (input.hidden-input)
```

### Non-Core Packages

```
goto-definition 1.3.4 
linter 2.3.0 
prettier-atom 0.57.0 
```

**Comment by gempers** [comment]
same issue!

**Comment by xaddict** [comment]
I'm getting this in 2020

[Enter steps to reproduce:]

1. Go to a file
2. Select Packages -> Prettier -> Debug

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.60.0


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /Users/luuklamers/.atom/packages/prettier-atom/dist/displayDebugInfo/index.js:27

TypeError: Cannot read property 'version' of undefined
    at getDebugInfo (/packages/prettier-atom/dist/displayDebugInfo/index.js:27:51)
    at HTMLElement.displayDebugInfo (/packages/prettier-atom/dist/displayDebugInfo/index.js:36:11)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349538)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348013)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725694)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733617)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -9:27.8.0 core:select-all (input.hidden-input)
     -9:27.3.0 auto-indent:apply (input.hidden-input)
  4x -9:25.9.0 core:save (input.hidden-input)
     -7:50.7.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-close.has-stack)
     -7:22.4.0 core:save (input.hidden-input)
     -7:07.7.0 tree-view:add-file (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:04.4.0 core:confirm (input.hidden-input)
     -6:45 core:paste (input.hidden-input)
     -6:44.6.0 core:save (input.hidden-input)
     -6:40.4.0 tree-view:move (li.file.entry.list-item.status-added.selected)
     -6:37.4.0 core:confirm (input.hidden-input)
  3x -6:36.7.0 core:save (input.hidden-input)
  2x -5:56.4.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-close.has-stack)
     -4:01.9.0 prettier:debug (atom-notification.error.icon.icon-flame.native-key-bindings.has-close.has-stack)
     -1:11.9.0 core:save (input.hidden-input)
     -1:04.6.0 prettier:debug (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
auto-indent 0.5.0 
emmet 2.4.3 
ide-php 0.7.18 
ide-typescript 0.9.1 
ide-vue 0.1.9 
language-vue 0.26.0 
linter 2.3.1 
linter-phpcs 1.7.6 
prettier-atom 0.60.0 
```

**Comment by tleul** [comment]
getting the same error also I am having a problem (failed to load plugin 'react' declared linter error atom ) 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.4
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.60.0


### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /home/administrator/.atom/packages/prettier-atom/dist/displayDebugInfo/index.js:27

TypeError: Cannot read property 'version' of undefined
    at getDebugInfo (/packages/prettier-atom/dist/displayDebugInfo/index.js:27:51)
    at HTMLElement.displayDebugInfo (/packages/prettier-atom/dist/displayDebugInfo/index.js:36:11)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349538)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:348013)
    at AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:725693)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:733616)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -5:48.2.0 core:cancel (input.hidden-input)
     -5:47.4.0 editor:consolidate-selections (input.hidden-input)
     -5:47.4.0 core:cancel (input.hidden-input)
     -5:47.2.0 editor:consolidate-selections (input.hidden-input)
     -5:47.2.0 core:cancel (input.hidden-input)
     -4:25.4.0 intentions:highlight (input.hidden-input)
     -4:23 core:save (input.hidden-input)
     -4:08.7.0 tree-view:copy (span.name.icon.icon-file-text)
     -4:06.0 tree-view:remove (span.name.icon.icon-file-text)
     -1:21.8.0 prettier:toggle-format-on-save (input.hidden-input)
     -1:19.4.0 intentions:highlight (input.hidden-input)
     -1:19.1.0 core:save (input.hidden-input)
  4x -1:18.5.0 editor:newline (input.hidden-input)
  2x -1:15.4.0 intentions:highlight (input.hidden-input)
     -1:12.4.0 core:save (input.hidden-input)
     -1:06.6.0 prettier:debug (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.1 
prettier-atom 0.60.0 
```

os ubuntu 18.04
