### ISSUE TITLE
Can't update to or install v0.58.1

### ISSUE THREAD

**Issue by akonwi** [prettier/prettier-atom#565]
I saw there was an update available and used the atom ui to update the package but it failed and showed this error:

```
Installing “prettier-atom@0.58.1” failed.Hide output…

npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akonwi/.atom/.apm/_logs/2019-11-04T20_21_05_062Z-debug.log
```

I uninstalled the package completely and attempted to just install the latest version and I get the same result and error.

**Comment by nickpresta** [comment]
Here's the debug logging from the `/Users/npresta/.atom/.apm/_logs/2019-11-04T20_58_50_715Z-debug.log` file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/npresta/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/npresta/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/prettier-atom/versions/0.58.1/tarball',
1 verbose cli   '--target=4.2.7',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v10.2.1
4 verbose npm-session 3cdb12965378f7b5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/prettier-atom/versions/0.58.1/tarball 664ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/prettier-atom/versions/0.58.1/tarball fetched in 686ms
9 timing stage:loadCurrentTree Completed in 825ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule prettier-atom@0.58.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/atom-text-buffer-range 104ms (from cache)
18 silly pacote range manifest for atom-text-buffer-range@^1.0.0 fetched in 108ms
19 silly resolveWithNewModule atom-text-buffer-range@1.0.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/global-modules 109ms (from cache)
21 silly pacote range manifest for global-modules@^2.0.0 fetched in 113ms
22 silly resolveWithNewModule global-modules@2.0.0 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/execa 114ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/atom-package-deps 118ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/ignore 117ms (from cache)
26 silly pacote range manifest for atom-package-deps@^5.1.0 fetched in 123ms
27 silly resolveWithNewModule atom-package-deps@5.1.0 checking installable status
28 silly pacote range manifest for execa@^1.0.0 fetched in 122ms
29 silly resolveWithNewModule execa@1.0.0 checking installable status
30 silly fetchPackageMetaData error for prettier-eslint@npm:@lewisl9029/prettier-eslint Invalid dependency type requested: alias
31 http fetch GET 304 https://registry.npmjs.org/atom-text-buffer-point 128ms (from cache)
32 silly pacote range manifest for ignore@^5.1.4 fetched in 126ms
33 silly resolveWithNewModule ignore@5.1.4 checking installable status
34 http fetch GET 304 https://registry.npmjs.org/lodash 128ms (from cache)
35 silly pacote range manifest for atom-text-buffer-point@^1.0.0 fetched in 134ms
36 silly resolveWithNewModule atom-text-buffer-point@1.0.0 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/@babel%2fruntime 138ms (from cache)
38 silly pacote range manifest for lodash@^4.17.13 fetched in 136ms
39 silly resolveWithNewModule lodash@4.17.15 checking installable status
40 http fetch GET 304 https://registry.npmjs.org/atom-linter 141ms (from cache)
41 silly pacote range manifest for @babel/runtime@^7.6.3 fetched in 144ms
42 silly resolveWithNewModule @babel/runtime@7.6.3 checking installable status
43 silly pacote range manifest for atom-linter@^10.0.0 fetched in 143ms
44 silly resolveWithNewModule atom-linter@10.0.0 checking installable status
45 http fetch GET 304 https://registry.npmjs.org/loophole 37ms (from cache)
46 silly pacote range manifest for loophole@^1.1.0 fetched in 39ms
47 silly resolveWithNewModule loophole@1.1.0 checking installable status
48 http fetch GET 304 https://registry.npmjs.org/prettier-stylelint 28ms (from cache)
49 silly pacote range manifest for prettier-stylelint@^0.4.2 fetched in 29ms
50 silly resolveWithNewModule prettier-stylelint@0.4.2 checking installable status
51 http fetch GET 304 https://registry.npmjs.org/read-pkg-up 32ms (from cache)
52 silly pacote range manifest for read-pkg-up@^6.0.0 fetched in 33ms
53 silly resolveWithNewModule read-pkg-up@6.0.0 checking installable status
54 http fetch GET 304 https://registry.npmjs.org/yarn-global-modules 30ms (from cache)
55 silly pacote range manifest for yarn-global-modules@^1.0.1 fetched in 31ms
56 silly resolveWithNewModule yarn-global-modules@1.0.1 checking installable status
57 http fetch GET 304 https://registry.npmjs.org/@lewisl9029%2fprettier-eslint 253ms (from cache)
58 silly pacote range manifest for @lewisl9029/prettier-eslint@^9.0.1 fetched in 254ms
59 silly resolveWithNewModule @lewisl9029/prettier-eslint@9.0.1 checking installable status
60 http fetch GET 304 https://registry.npmjs.org/prettier 139ms (from cache)
61 silly pacote version manifest for prettier@1.18.2 fetched in 141ms
62 silly resolveWithNewModule prettier@1.18.2 checking installable status
63 timing stage:rollbackFailedOptional Completed in 1ms
64 timing stage:runTopLevelLifecycles Completed in 1104ms
65 silly saveTree apm-install-dir-119104-29325-24vz0e.54zqf
65 silly saveTree └─┬ prettier-atom@0.58.1
65 silly saveTree   ├── @babel/runtime@7.6.3
65 silly saveTree   ├─┬ @lewisl9029/prettier-eslint@9.0.1
65 silly saveTree   │ └── prettier@1.18.2
65 silly saveTree   ├── atom-linter@10.0.0
65 silly saveTree   ├── atom-package-deps@5.1.0
65 silly saveTree   ├── atom-text-buffer-point@1.0.0
65 silly saveTree   ├── atom-text-buffer-range@1.0.0
65 silly saveTree   ├── execa@1.0.0
65 silly saveTree   ├── global-modules@2.0.0
65 silly saveTree   ├── ignore@5.1.4
65 silly saveTree   ├── lodash@4.17.15
65 silly saveTree   ├── loophole@1.1.0
65 silly saveTree   ├── prettier-stylelint@0.4.2
65 silly saveTree   ├── prettier@1.18.2
65 silly saveTree   ├── read-pkg-up@6.0.0
65 silly saveTree   └── yarn-global-modules@1.0.1
66 verbose stack Error: Invalid dependency type requested: alias
66 verbose stack     at getFetcher (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/pacote/lib/fetch.js:68:15)
66 verbose stack     at manifest (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/pacote/lib/fetch.js:15:19)
66 verbose stack     at pinflight (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/pacote/manifest.js:24:12)
66 verbose stack     at /Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
66 verbose stack     at Promise._execute (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:303:9)
66 verbose stack     at Promise._resolveFromExecutor (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:483:18)
66 verbose stack     at new Promise (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)
66 verbose stack     at _inflight (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
66 verbose stack     at /Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
66 verbose stack     at tryCatcher (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
66 verbose stack     at Promise._settlePromiseFromHandler (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
66 verbose stack     at Promise._settlePromise (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
66 verbose stack     at Promise._settlePromiseCtx (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
66 verbose stack     at Async._drainQueue (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
66 verbose stack     at Async._drainQueues (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
66 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
67 verbose cwd /private/var/folders/b7/q2cys3x11cz7ydd0j5xf1qd40000gp/T/apm-install-dir-119104-29325-24vz0e.54zqf
68 verbose Darwin 18.7.0
69 verbose argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/npresta/.atom/.apm/.apmrc" "--userconfig" "/Users/npresta/.atom/.apmrc" "install" "https://www.atom.io/api/packages/prettier-atom/versions/0.58.1/tarball" "--target=4.2.7" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
70 verbose node v10.2.1
71 verbose npm  v6.2.0
72 error Invalid dependency type requested: alias
73 verbose exit [ 1, true ]
```

**Comment by robwise** [comment]
Sorry about that, there's no way to test that until we publish to APM apparently (didn't get that error when running the package in dev mode before publishing).

I've unpublished that version for now. Please revert back to the latest published version (0.58.0).

@lewisl9029 Do you know of a different way of linking the package without using the alias command so that we can sidestep this issue?

**Comment by lewisl9029** [comment]
Ah sorry about that, completely forgot apm was coupled to npm. Was working fine when I linked it to my local `yarn install`ed directory, but makes sense that it'd break when actually installed by apm.

The alias was mostly just a shortcut to avoid having to change references to `prettier-eslint` in the code for the most part, to make it painless to revert back and minimize chance for conflicts. If we can't make use of that we could update all the references to use `@lewisl9029/prettier-eslint` manually instead. I'll whip up another PR.

**Comment by lewisl9029** [comment]
PR ready: https://github.com/prettier/prettier-atom/pull/566
