### ISSUE TITLE
Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../Projects/hacke...

### ISSUE THREAD

**Issue by jonbackhaus** [prettier/prettier-atom#576]
[Enter steps to reproduce:]

1. Open project

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.58.2

### Stack Trace

Uncaught RangeError: path should be a `path.relative()`d string, but got "../../../Projects/hacker-laws/README.md"

```
At /Users/Jonathan/dotfiles/atom/.atom/packages/prettier-atom/node_modules/ignore/index.js:337

RangeError: path should be a `path.relative()`d string, but got "../../../Projects/hacker-laws/README.md"
    at throwError (/packages/prettier-atom/node_modules/ignore/index.js:337:9)
    at checkPath (/packages/prettier-atom/node_modules/ignore/index.js:356:12)
    at Ignore._test (/packages/prettier-atom/node_modules/ignore/index.js:473:5)
    at Ignore.ignores (/packages/prettier-atom/node_modules/ignore/index.js:512:17)
    at one (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:255:51)
    at handleIgnore (/packages/linter-markdown/node_modules/unified-engine/lib/finder.js:243:5)
    at done (/packages/linter-markdown/node_modules/unified-engine/lib/ignore.js:41:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at apply (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:190:7)
    at applyAll (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:180:7)
    at found (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:172:7)
    at next (/packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:122:11)
    at /packages/linter-markdown/node_modules/unified-engine/lib/find-up.js:140:18)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
```

### Commands

```
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-xmlvalidate 0.5.0 
autocomplete-ansible 0.1.24 
busy-signal 2.0.1 
circle-ci 0.10.1 
docker 0.8.0 
file-icons 2.1.36 
git-history 3.3.0 
git-line 0.6.0 
git-plus 8.7.1 
git-time-machine 2.1.0 
intentions 1.1.5 
language-ansible 0.2.2 
language-docker 1.1.8 
language-ini 1.23.0 
language-markdown 0.37.0 
linter 2.3.1 
linter-ansible-linting 1.5.0 
linter-docker 0.3.2 
linter-markdown 5.2.10 
linter-ui-default 1.8.0 
markdown-preview-plus 3.11.3 
nord-atom-ui 0.12.0 
platformio-ide-terminal 2.10.0 
prettier-atom 0.58.2 
split-diff 1.6.1 
structure-view 0.2.1 
```

**Comment by DerZyklop** [comment]
Probably related to https://github.com/prettier/prettier-atom/issues/627
