### ISSUE TITLE
prettier-atom fails while being activated

### ISSUE THREAD

**Issue by eddykaya** [prettier/prettier-atom#625]
I installed the prettier-atom package but it fails while activating with the following error:

[Enter steps to reproduce:]

1. install prettier-atom package

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 19.04
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.58.2

### Stack Trace

Failed to activate the prettier-atom package

```
At Unexpected token ...

SyntaxError: Unexpected token ...
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/prettier-atom/node_modules/@lewisl9029/prettier-eslint/dist/index.js:15:44)
    at /packages/prettier-atom/node_modules/@lewisl9029/prettier-eslint/dist/index.js:248:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:15:24)
    at /packages/prettier-atom/dist/executePrettier/executePrettierOnBufferRange.js:165:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/prettier-atom/dist/executePrettier/index.js:3:38)
    at /packages/prettier-atom/dist/executePrettier/index.js:8:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
```

### Commands

```
     -8:51.1.0 core:confirm (input.hidden-input)
     -8:51.1.0 linter:lint (input.hidden-input)
     -8:49.3.0 command-palette:toggle (input.hidden-input)
     -8:48.3.0 core:move-down (input.hidden-input)
     -8:47.8.0 core:move-up (input.hidden-input)
     -8:47.1.0 core:confirm (input.hidden-input)
     -8:47.1.0 linter-eslint:debug (input.hidden-input)
     -8:22.4.0 command-palette:toggle (input.hidden-input)
     -8:21.2.0 core:move-down (input.hidden-input)
     -8:20.9.0 core:confirm (input.hidden-input)
     -8:20.9.0 linter:debug (input.hidden-input)
     -6:04.9.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -5:44.2.0 tabs:close-all-tabs (div.title)
     -5:29.6.0 core:confirm (input.hidden-input)
     -2:32.5.0 core:select-all (input.hidden-input)
     -2:29.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 12.5.3 
busy-signal 2.0.1 
compare-files 0.8.1 
editorconfig 2.5.0 
git-diff-details 1.4.0 
git-plus 8.1.0 
intentions 1.1.5 
language-babel 2.85.0 
language-nginx 0.8.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.0 
prettier-atom 0.58.2 
```

I don't know what is wrong with it, can anyone help?

**Comment by eddykaya** [comment]
I saw I used an old atom version, the issue is gone after upgrading to 1.4.0
