### ISSUE TITLE
Uncaught Error: Cannot find module './config-schema.json'Require stack:- $ATOM_HOME/packages\pr...

### ISSUE THREAD

**Issue by AnatoliyKhaulin** [prettier/prettier-atom#820]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.60.1

### Stack Trace

Uncaught Error: Cannot find module './config-schema.json'
Require stack:
- C:\Users\anatoly\.atom\packages\prettier-atom\dist\main.js
- C:\Users\anatoly\AppData\Local\atom\app-1.48.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module './config-schema.json'
Require stack:
- C:\Users\anatoly\.atom\packages\prettier-atom\dist\main.js
- C:\Users\anatoly\AppData\Local\atom\app-1.48.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:155487)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:146819)
    at /packages/prettier-atom/dist/main.js:8:16)
    at /packages/prettier-atom/dist/main.js:124:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:735013)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3308385)
    at Package.activateConfig (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:3297673)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:920272)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2543559)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2533839)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2533662)
    at new PackageCard (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2525259)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:755194)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:755761)
    at new PackageDetailView (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:752347)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:942351)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:943072)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:942996)
    at SettingsView.initializePanels (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:940453)
    at ~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:937629
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
ide-vue 0.1.9 
intentions 1.1.5 
language-pug 0.0.22 
language-vue 0.26.0 
linter 2.3.1 
linter-pug-lint 0.2.0 
linter-sass-lint 1.9.0 
linter-ui-default 1.8.1 
prettier-atom 0.60.1 
```

**Comment by robwise** [comment]
Doing some issues clean-up. If this is still an issue, please re-open.
