### ISSUE TITLE
Uncaught Error: Cannot find module './third-party.js'

### ISSUE THREAD

**Issue by rvantonisse-accessibility** [prettier/prettier-atom#881]
Hey, I started with Svelte development and for this project I want to use Prettier to apply consistent formatting. Unfortunately, provided with current configuration, prettier-atom throws an error.

I got a feeling it may be caused by the [prettier-plugin-svelte](https://github.com/sveltejs/prettier-plugin-svelte), but because I could not find any direct relation to this plugin, I filed the issue here.

If you are interested in the project configuration that is used, it is a fork of w3c/wcag-em-report-tool at [accessibilityNL/wcag-em-report-tool](https://github.com/AccessibilityNL/wcag-em-report-tool/tree/feature/rebuild-svelte) at a rebuild-svelte branch.

All required debug info I could think of is in following contents.

Reproducing the error:

1. Open any js / svelte / json file
2. Use prettier:format (`ctrl-alt-f`)
3. -> error

Does prettier-atom work in other contexts?:

- In projects without prettier configuration, does not run. (expected with configuration)
- In projects without prettier configuration, disabling "format only..." options, files are prettified using default prettier configuration.
- Running prettier within prettier-atom project files, works as intended.

prettier-atom configuration:

```cson
  "prettier-atom":
    formatOnSaveOptions:
      isDisabledIfNoConfigFile: true
      isDisabledIfNotInPackageJson: true
    prettierEslintOptions:
      prettierLast: true
    useEslint: true
    useStylelint: true
```

My packages concerning Prettier configuration:
```json
{
        "prettier": "^2.1.1",
        "prettier-plugin-svelte": "^1.2.1"
}
```

.prettierrc.js:
```javascript
module.exports = {

  // EditorConfig
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": true,
  "overrides": [],

  // Svelte
  "svelteSortOrder" : "markup-styles-scripts",
  "svelteStrictMode": true,
  "svelteBracketNewLine": true,
  "svelteAllowShorthand": false,
  "svelteIndentScriptAndStyle": true
};
```

Atom debug output:
<details>

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.3
**Thrown From**: [prettier-atom](https://github.com/prettier/prettier-atom) package 0.60.1

### Stack Trace

Uncaught Error: Cannot find module './third-party.js'
Require stack:
- /Users/<MY_USERNAME>/Projects/accessibility/wcag-em-report-tool/node_modules/prettier/index.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/helpers/getPrettierInstance.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/helpers/index.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/statusTile/updateStatusTileScope.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/statusTile/index.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module './third-party.js'
Require stack:
- /Users/<MY_USERNAME>/Projects/accessibility/wcag-em-report-tool/node_modules/prettier/index.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/helpers/getPrettierInstance.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/helpers/index.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/statusTile/updateStatusTileScope.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/statusTile/index.js
- /Users/<MY_USERNAME>/.atom/packages/prettier-atom/dist/main.js
- /Applications/Atom.app/Contents/Resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at Object.<anonymous> (/Users/<MY_USERNAME>/Projects/accessibility/wcag-em-report-tool/node_modules/prettier/index.js:16551:18)
    at Object.<anonymous> (/Users/<MY_USERNAME>/Projects/accessibility/wcag-em-report-tool/node_modules/prettier/index.js:54745:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at requireWithFallbackToBundledPrettier (/packages/prettier-atom/dist/helpers/getPrettierInstance.js:21:23)
    at /packages/prettier-atom/node_modules/lodash/lodash.min.js:56:306
    at /packages/prettier-atom/node_modules/lodash/lodash.min.js:56:276
    at /packages/prettier-atom/node_modules/lodash/lodash.min.js:9:88)
    at /packages/prettier-atom/node_modules/lodash/lodash.min.js:106:489
    at /packages/prettier-atom/node_modules/lodash/lodash.min.js:9:88)
    at /packages/prettier-atom/node_modules/lodash/lodash.min.js:72:58
    at /packages/prettier-atom/dist/main.js:72:17)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349780)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1230988)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1227122)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284829)
```

### Commands

```
     -8:13.6.0 prettier:format (input.hidden-input)
     -8:03.6.0 docblockr:parse-enter (input.hidden-input)
     -8:03.6.0 editor:newline (input.hidden-input)
  2x -7:42 editor:move-to-end-of-screen-line (input.hidden-input)
     -7:34 prettier:format (input.hidden-input)
     -6:47.9.0 project-find:show-in-current-directory (span.name.icon.node-icon)
     -6:43.9.0 core:backspace (input.hidden-input)
     -6:38.7.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -6:33.4.0 find-and-replace:focus-next (input.hidden-input)
     -6:32.9.0 core:backspace (input.hidden-input)
     -6:31.9.0 core:confirm (input.hidden-input)
  2x -5:13.8.0 core:save (input.hidden-input)
     -5:03.5.0 intentions:highlight (input.hidden-input)
     -5:03.0 prettier:format (input.hidden-input)
     -4:37.6.0 settings-view:open (input.hidden-input)
  2x -2:44.7.0 prettier:format (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
chameleon-ui 2.0.0 
color-picker 2.3.0 
date 2.6.0 
developer-day-syntax 0.2.0 
developer-night-syntax 0.1.0 
docblockr 0.13.7 
editorconfig 2.6.1 
emmet 2.4.3 
file-icons 2.1.42 
git-blame 1.8.0 
ide-svelte 0.1.1 
intentions 1.1.5 
language-apache 1.8.0 
language-babel 2.85.0 
language-generic-config 1.4.0 
language-nunjucks 4.2.1 
language-postcss 1.3.1 
language-twig 1.6.4 
linter 2.3.1 
linter-eslint 8.5.5 
linter-stylelint 4.5.1 
linter-ui-default 1.8.1 
minimap 4.29.9 
minimap-git-diff 4.3.1 
prettier-atom 0.60.1 
snippet-generator 0.3.2 
theme-switch 0.6.0 
transform 0.4.0 
triad-dark-syntax 0.2.1 
triad-light-syntax 0.2.1 
```
</details>

Prettier: Debug output:

<details>

  Atom version: 1.50.0,
  prettier-atom version: 0.60.1
  prettier: bundled
  prettier version: 2.0.5
  prettier-eslint version: 9.0.1
  prettier-atom configuration: 

  ```json
  {
    "formatOnSaveOptions": {
      "isDisabledIfNoConfigFile": true,
      "isDisabledIfNotInPackageJson": true,
      "enabled": false,
      "respectEslintignore": true,
      "showInStatusBar": false,
      "excludedGlobs": [],
      "whitelistedGlobs": [],
      "ignoreNodeModules": true
    },
    "prettierEslintOptions": {
      "prettierLast": true
    },
    "useEslint": true,
    "useStylelint": true,
    "useEditorConfig": true
  }
  ```
</details>

Hope I could be of any help, your package is of great help to me!

Keep up the good work! 💪

**Comment by rvantonisse-accessibility** [comment]
**UPDATE**: Rolling back to prettier-atom@0.54.0 resolved this issue.

However, I would like to be up to date with all of my packages. So, if a sollution would be provided for versions >0.54.0, I would be really gratefull!

Thank you.

**Comment by robwise** [comment]
Your prettier version is outdated (`2.0.5`). in order to use the latest version of prettier-atom, make sure to update it.

**Comment by rvantonisse-accessibility** [comment]
At the time of intalling and setup version 2.0.5 was the latest version.

Tested with the reproduce steps: with prettier version 2.1.1 and atom prettier 0.60.1 formatting works without throwing an error! 👍 

Thank you!
